//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatableJquery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string firstname { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string lastname { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string birthday { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string email { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public decimal phone { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string company { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public decimal zipcode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
